-- Ejercicio 8.
-- Queremos auditar, por cada fila insertada en la tabla Publishers, fecha y hora de alta y
-- usuario que realizó la misma (tal como hicimos en el Ejercicio 6). Podemos optar por:
-- A. Agregar dos columnas adicionales a la tabla Publishers (tal como hicimos en el Ejercicio
-- 6) o bien
-- B. Tener una tabla de log independiente (como la tabla Registro del Ejercicio 7).
-- ¿Que configuración de trigger PL/pgSQL elegiría si se adopta la opción A?
-- ¿Que configuración de trigger PL/pgSQL elegiría si se adopta la opción B?